# Generated by Django 2.2.6 on 2019-11-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='savings',
            name='month',
            field=models.IntegerField(max_length=15),
        ),
    ]
